### ISSUE TITLE
jasperreports-server can not be deployed

### ISSUE THREAD

**Issue by yongk** [Robinyo/js-docker#1]
Hi, 
tomcat reports 
```
Caused by: java.util.zip.ZipException: invalid END header (bad central directory offset)
                at java.base/java.util.zip.ZipFile$Source.zerror(ZipFile.java:1535)
                at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1458)
                at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1274)
                at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1237)
                at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:727)
                at java.base/java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:844)
                at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:247)
                at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:177)
                at java.base/java.util.jar.JarFile.<init>(JarFile.java:348)
                ... 51 more
```

it seems that open-sans-fonts-extension.jar is corrupted.
```
$ unzip -t open-sans-fonts-extension.jar
Archive:  open-sans-fonts-extension.jar
error [open-sans-fonts-extension.jar]:  missing 3 bytes in zipfile
  (attempting to process anyway)
error [open-sans-fonts-extension.jar]:  attempt to seek before beginning of zipfile
  (please check that you have transferred or created the zipfile in the
  appropriate BINARY mode and that you have compiled UnZip properly)
  (attempting to re-compensate)
    testing: jasperreports_extension.properties   OK
    testing: fonts/OpenSans/OpenSans-Light.ttf   bad CRC 4ae3134f  (should be e70f05f5)
file #3:  bad zipfile offset (local header sig):  61199
  (attempting to re-compensate)
file #3:  bad zipfile offset (local header sig):  61199
file #4:  bad zipfile offset (local header sig):  123240
    testing: fonts/OpenSans/OpenSans-BoldItalic.ttf   OK
    testing: fonts/fontsfamily1592346500512.xml   OK
At least one error was detected in open-sans-fonts-extension.jar.
```

**Comment by Robinyo** [comment]
I can download the [file](https://github.com/Robinyo/js-docker/blob/master/assets/libs/open-sans-fonts-extension.jar) from the GitHub repo and unpack it without any issues?

**Comment by yongk** [comment]
@Robinyo thanks for your reply.

I downloaded the [file](https://github.com/Robinyo/js-docker/blob/master/assets/libs/open-sans-fonts-extension.jar)  and the problem still exits.

I also use 7zip to unpack the file and failed again.

my file's md5 is bd2da38cf6915bbbdc60a975e0e79e1f, could you please give me you file's md5 code?

**Comment by Robinyo** [comment]
Hey @yongk 

You can follow the steps in the JasperSoft [wiki](https://community.jaspersoft.com/wiki/custom-font-font-extension) to generate a font extension.

Also see: [Working with Jaspersoft Studio](https://github.com/Robinyo/serendipity-api/blob/master/projects/spring-boot/docs/administrator/jaspersoft-studio.md)
